# Sphinx configuration — auto-generated by doc_workflow_runner.py
# Do not edit manually; regenerate by re-running the workflow.
project   = 'sample_codebase'
author    = 'Documentation Agent'
release   = '0.1'
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
]
html_theme = 'alabaster'
